# Generated by Django 5.1.1 on 2026-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('lv', 'Latvian'), ('en', 'English')], default='lv', max_length=5),
        ),
    ]
